/**
 * lib/demo/listings.ts — FitBodega demo seed
 * Sample Vancouver listings used by the mock Supabase client when no
 * database is configured (local preview) — and as the go-live seed base.
 * Names are fictional, drawn from the brand mockups.
 */
import type { Listing } from "@/lib/supabase/types";

const NOW = "2026-07-10T12:00:00.000Z";

function listing(partial: Partial<Listing> & Pick<Listing, "id" | "name" | "slug" | "type">): Listing {
  return {
    created_at: NOW,
    updated_at: NOW,
    description: null,
    long_description: null,
    tagline: null,
    logo_url: null,
    images: [],
    website: null,
    email: null,
    phone: null,
    address: null,
    city: "Vancouver",
    country: "Canada",
    latitude: 49.2827,
    longitude: -123.1207,
    specialties: [],
    experience_levels: ["All Levels"],
    languages: ["English"],
    price_range: null,
    social_instagram: null,
    social_facebook: null,
    social_youtube: null,
    status: "approved",
    is_featured: false,
    is_verified: false,
    owner_id: null,
    view_count: 0,
    rating_avg: 0,
    rating_count: 0,
    stripe_customer_id: null,
    stripe_subscription_id: null,
    plan: "free",
    plan_expires_at: null,
    certification_id: null,
    last_featured_at: null,
    ...partial,
  };
}

export const DEMO_LISTINGS: Listing[] = [
  listing({
    id: "demo-01", name: "Zenith Lab", slug: "zenith-lab", type: "recovery",
    tagline: "Contrast therapy circuits, red light, and performance diagnostics.",
    description: "A recovery sanctuary in Mount Pleasant. Cedar sauna, twin cold plunges, red light suites, and DEXA scanning for those who treat recovery as training.",
    specialties: ["Cold Plunge", "Infrared Sauna", "Red Light Therapy", "DEXA / VO2 Max"],
    images: ["/demo/zenith-lab.svg"], price_range: "$$$",
    is_featured: true, is_verified: true, rating_avg: 4.8, rating_count: 63,
    address: "Mount Pleasant", city: "Vancouver",
  }),
  listing({
    id: "demo-02", name: "The Banya House", slug: "the-banya-house", type: "recovery",
    tagline: "Eastern European heat rituals. Aufguss, banya, and ice.",
    description: "Traditional banya culture in a modern West Coast space — guided Aufguss rounds, plunge pools, and rest lounges.",
    specialties: ["Banya", "Aufguss", "Ice Bath", "Contrast Therapy"],
    images: ["/demo/banya-house.svg"], price_range: "$$",
    is_featured: true, is_verified: true, rating_avg: 4.9, rating_count: 88,
    address: "Chinatown", city: "Vancouver",
  }),
  listing({
    id: "demo-03", name: "Float North", slug: "float-north", type: "recovery",
    tagline: "Sensory deprivation and hyperbaric recovery on the North Shore.",
    specialties: ["Float Tank", "Hyperbaric Oxygen", "Compression Therapy"],
    images: ["/demo/float-north.svg"], price_range: "$$",
    is_verified: true, rating_avg: 4.7, rating_count: 41,
    city: "North Vancouver",
  }),
  listing({
    id: "demo-04", name: "Iron Archive", slug: "iron-archive", type: "gym",
    tagline: "A strength library. Barbells, platforms, and no machines you don't need.",
    description: "Downtown's dedicated strength floor — calibrated plates, competition racks, and coaching for powerlifting and olympic lifting.",
    specialties: ["Powerlifting", "Olympic Weightlifting", "Functional Strength"],
    images: ["/demo/iron-archive.svg"], price_range: "$$",
    is_featured: true, is_verified: true, rating_avg: 4.6, rating_count: 112,
    address: "Downtown", city: "Vancouver",
  }),
  listing({
    id: "demo-05", name: "Void Boxing", slug: "void-boxing", type: "gym",
    tagline: "Industrial aesthetics meet high-performance combat training.",
    specialties: ["Boxing", "Kickboxing", "Muay Thai"],
    images: ["/demo/void-boxing.svg"], price_range: "$$",
    is_featured: true, is_verified: true, rating_avg: 5.0, rating_count: 74,
    address: "Strathcona", city: "Vancouver",
  }),
  listing({
    id: "demo-06", name: "Flow State Pilates", slug: "flow-state-pilates", type: "gym",
    tagline: "Reformer work for athletes — mobility as a discipline.",
    specialties: ["Reformer Pilates", "Mobility", "Breathwork"],
    images: ["/demo/flow-state.svg"], price_range: "$$$",
    is_verified: true, rating_avg: 4.6, rating_count: 39,
    address: "Kitsilano", city: "Vancouver",
  }),
  listing({
    id: "demo-07", name: "The Summit Athletic Club", slug: "the-summit-athletic-club", type: "gym",
    tagline: "Elite conditioning. HIIT, rowing, and altitude training.",
    specialties: ["HIIT", "Circuit Training", "Rowing"],
    images: ["/demo/the-summit.svg"], price_range: "$$$$",
    is_featured: true, rating_avg: 4.9, rating_count: 56,
    address: "Coal Harbour", city: "Vancouver",
  }),
  listing({
    id: "demo-08", name: "Marcus Vance", slug: "marcus-vance", type: "trainer",
    tagline: "Elite performance coach. High-threshold strength and metabolic conditioning.",
    description: "12 years, 450+ clients. Marcus fuses brutalist physical principles with modern physiological science to rebuild the human machine from the ground up.",
    specialties: ["Functional Strength", "Sports Nutrition", "Athletic Development"],
    images: ["/demo/marcus-vance.svg"], price_range: "$$$",
    is_featured: true, is_verified: true, rating_avg: 5.0, rating_count: 47,
    city: "Vancouver",
  }),
  listing({
    id: "demo-09", name: "Sara Blanc", slug: "sara-blanc", type: "trainer",
    tagline: "Mobility specialist — fascial release and active range of motion.",
    specialties: ["Mobility", "Stretching", "Athletic Therapy"],
    images: ["/demo/sara-blanc.svg"], price_range: "$$",
    is_verified: true, rating_avg: 4.8, rating_count: 29,
    city: "Vancouver",
  }),
  listing({
    id: "demo-13", name: "The Sunday Run Club", slug: "the-sunday-run-club", type: "club",
    tagline: "Elevated community movement. Every Sunday at 07:00.",
    description: "A run crew for those who show up. All paces, one standard — consistency. Coffee after, always.",
    specialties: ["Run Club", "Social Wellness Club"],
    images: ["/demo/sunday-run-club.svg"], price_range: "$",
    is_featured: true, is_verified: true, rating_avg: 4.9, rating_count: 52,
    address: "Seawall", city: "Vancouver",
  }),
  listing({
    id: "demo-14", name: "Pacific Masters Swim", slug: "pacific-masters-swim", type: "club",
    tagline: "Structured masters swim — technique, threshold, and open water.",
    specialties: ["Masters Swim", "Swim Club", "Triathlon Club"],
    images: ["/demo/pacific-masters.svg"], price_range: "$$",
    is_verified: true, rating_avg: 4.7, rating_count: 26,
    city: "Vancouver",
  }),
  listing({
    id: "demo-10", name: "Meridian Nutrition", slug: "meridian-nutrition", type: "nutritionist",
    tagline: "Registered dietitians for training, recovery, and body composition.",
    specialties: ["Sports Nutrition", "Registered Dietitian", "Meal Prep"],
    images: ["/demo/meridian.svg"], price_range: "$$",
    is_verified: true, rating_avg: 4.7, rating_count: 22,
    address: "Fairview", city: "Vancouver",
  }),
  listing({
    id: "demo-11", name: "The Apothecary Pantry", slug: "the-apothecary-pantry", type: "store",
    tagline: "Pure compounds, zero fillers — supplements and whole-food fuel.",
    specialties: ["Supplements", "Health Foods"],
    images: ["/demo/apothecary.svg"], price_range: "$$",
    rating_avg: 4.5, rating_count: 18,
    address: "Main Street", city: "Vancouver",
  }),
  listing({
    id: "demo-12", name: "Pacific Rise FC Academy", slug: "pacific-rise-fc-academy", type: "youth",
    tagline: "Technical soccer development for U6–U18 — pathways, not promises.",
    description: "Licensed coaches, small-group technical sessions, and a clear development pathway from grassroots to high performance.",
    specialties: ["Soccer Academies", "Private Coaching", "Camps"],
    images: ["/demo/pacific-rise.svg"], price_range: "$$",
    is_featured: true, is_verified: true, rating_avg: 4.9, rating_count: 35,
    city: "Vancouver",
  }),
];
